#!/usr/bin/python
#Simple script to push ted data to cosm
# $Id$
import ConfigParser
import ted
import cosm
import time
import daemon

TEDCONFIG="/etc/ted.conf"

def main():
      config = ConfigParser.ConfigParser()
      config.read(TEDCONFIG)

      t = ted.Ted(config.get("DEVICE","HOST"))
      
      while True:
            t.update()
            c = cosm.Cosm(config.get("CREDENTIALS","FEED"),
                          config.get("CREDENTIALS","KEY"))
            c.addDatapoint("Watts",t.getWatts())
            c.addDatapoint("Volts",t.getVolts())
            c.buildUpdate()
            c.sendUpdate()
            time.sleep(30)


with daemon.DaemonContext():
      main()
